name: Daily Run

on:
  schedule:
    - cron: "0 23 * * *"  # 7 PM Eastern

permissions:
  contents: write

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Run Python script
        run: python get_random_puzzle.py 

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Auto update on $(date -u)" || echo "No changes"
          git push
